// <auto-generated />
namespace Photo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Task_10_PhotographerRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Task_10_PhotographerRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "201703091642344_Task_10_PhotographerRoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
