USE [master]
GO

/****** Object:  Database [CarDealerSystem]    Script Date: 5.11.2017 г. 14:43:50 ******/
CREATE DATABASE [CarDealerSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CarDealerSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\CarDealerSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CarDealerSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\CarDealerSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CarDealerSystem] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CarDealerSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CarDealerSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CarDealerSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CarDealerSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CarDealerSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CarDealerSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [CarDealerSystem] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CarDealerSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CarDealerSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CarDealerSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CarDealerSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CarDealerSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CarDealerSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CarDealerSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CarDealerSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CarDealerSystem] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CarDealerSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CarDealerSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CarDealerSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CarDealerSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CarDealerSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CarDealerSystem] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [CarDealerSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CarDealerSystem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CarDealerSystem] SET  MULTI_USER 
GO

ALTER DATABASE [CarDealerSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CarDealerSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CarDealerSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CarDealerSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CarDealerSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CarDealerSystem] SET QUERY_STORE = OFF
GO

USE [CarDealerSystem]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [CarDealerSystem] SET  READ_WRITE 
GO

